services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra-node
    ports:
      - "9042:9042"   # CQL port
      - "7000:7000"   # Cluster communication (unsecured)
      - "7001:7001"   # Cluster communication (secured)
      - "7199:7199"   # JMX monitoring
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      # - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator #cassandra:cassandra by default
    # volumes:
    #   - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra-net

  cassandra-web:
    image: ipushc/cassandra-web
    container_name: cassandra-web
    depends_on:
      cassandra:
        condition: service_started
    ports:
      - "3050:80"
    environment:
      HOST_PORT: ":80"
      # READ_ONLY: false 
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      # CASSANDRA_USERNAME: cassandra
      # CASSANDRA_PASSWORD: cassandra
      # APP_PATH: path
    networks:
      - cassandra-net


networks:
  cassandra-net: