services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: tna.work10@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8084:80"
    # volumes:
    #   - pgadmin_data:/var/lib/pgadmin

# volumes:
#   pgadmin_data: