services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      #- POSTGRES_LOGGING_LEVEL=all
      # - PGOPTIONS="-c log_statement=all -c log_duration=on"
    volumes:
    - pg_vol:/var/lib/postgresql/data  # Persist data with a volume
    ports:
      - "5432:5432"

volumes:
  pg_vol:
    driver: local