services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    # network_mode: "host"  # чтобы пользовать адресом localhost вместо host.docker.internal
    ports:
      - "8085:8080"
    command: start-dev # Start Keycloak in development mode
    environment:
      # Database-related configuration
      KC_DB: postgres
      # KC_DB_URL: jdbc:postgresql://${IZHG_DB_POSTGRES_SERVER_DEV}:${IZHG_DB_POSTGRES_PORT_DEV}/keycloak #db должна существовать
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak
      KC_DB_USERNAME: ${IZHG_DB_POSTGRES_USER_DEV}
      KC_DB_PASSWORD: ${IZHG_DB_POSTGRES_PASSWORD_DEV}
      KC_HOSTNAME: localhost
      # KC_HOSTNAME_PORT: 8085
      # Admin user credentials
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin